name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Injetar Segredos no HTML e JS
        run: |
          # 1. Injeta a API no app.js
          sed -i "s|API_URL_SECRET|${{ secrets.API_GAS_URL }}|g" app.js
          
          # 2. Injeta os Links de Template no index.html
          sed -i "s|LINK_EXCEL_SECRET|${{ secrets.LINK_EXCEL }}|g" index.html
          sed -i "s|LINK_PLANILHA_SECRET|${{ secrets.LINK_PLANILHA }}|g" index.html

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
