name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Injetar URL Segura no Código
        run: |
          sed -i 's|__API_URL_SECRET__|${{ secrets.API_GAS_URL }}|g' index.html
          sed -i 's|__LINK_EXCEL_SECRET__|${{ secrets.LINK_EXCEL }}|g' index.html
          sed -i 's|__LINK_PLANILHA_SECRET__|${{ secrets.LINK_PLANILHA }}|g' index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
